### ISSUE TITLE
Add a codecov badge to this repository, and analyze the commits with codecov

### ISSUE THREAD

**Issue by ollie-iterators** [internetarchive/iaux-search-service#28]
I noticed that this repository has a way to check the code coverage on codecov: https://app.codecov.io/gh/internetarchive/iaux-search-service, but I don't see a codecov badge on this repository.

It would also be good if the commits were analyzed with codecov for this repository, like the others.

**Comment by latonv** [comment]
Thanks for pointing this out! I've added the badge and updated the default branch on codecov so that it should properly show commit coverage now.
