### ISSUE TITLE
Tried running it but getting the below error

### ISSUE THREAD

**Issue by ali-habibzadeh** [internetarchive/iaux-search-service#3]
```
index.js:1
export { Metadata } from './src/models/metadata';
^^^^^^

SyntaxError: Unexpected token 'export'
```

running from ts-node. Code has nothing except `import { SearchService } from "@internetarchive/search-service";`

**Comment by ali-habibzadeh** [comment]
I guess while I am here, the docs seems to be old and is not matching the actual code

**Comment by jbuckner** [comment]
I have not tried using this in node, only in the browser. It's an es module. Does node support that?

What docs are incorrect?

**Comment by jbuckner** [comment]
Closing this. Please reopen with more details.
